name: Run STARS Submission Checks
# Improvements
# ------------
# Change disallowed file script to allow folders to be blocked
# Determine which files should be in disallowed files script


on: [push, pull_request]  # Trigger on push and PRs
# on: [pull_request]  # Trigger on PRs

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch the full history

    - name: Confirm only changes in allowed files
      run: |
        
        # When merging teams' files together, common editing of files causes issues.

        # Commit with most up to date common files. Do not change unless you are working on the post-program integration team or have explicit permission from someone who is.
        BASE_COMMIT="1ee8b8ddc79916972c0de34d0fa28f3dfec7c3fb" #6/17/2025
        
        # Get list of changed files between the base commit and current commit
        git diff --name-only $BASE_COMMIT ${{ github.sha }} > changed_files.txt
        
        # List of files teams shouldn't change
        BLOCKED_FILES=(".github/scripts/requirements.txt" \
                        "verilog/rtl/Makefile" \
                        "verilog/includes/includes.rtl.global" \
                        "verilog/includes/includes.gl.global" \
                        "verilog/rtl/ffram/ffram_WB_Wrapper.sv" \
                        "verilog/rtl/ffram/ffram_WB.sv" \
                        "verilog/rtl/ffram/ffram.sv" \
                        "verilog/rtl/ffram/ffram.yml" \
                        "verilog/rtl/ffram/ffram.yml" \
                        "verilog/rtl/gpio_control/gpio_control_WB.sv" \
                        "verilog/rtl/gpio_control/gpio_control_WB.v" \
                        "verilog/rtl/gpio_control/gpio_control_Wrapper.v" \
                        "verilog/rtl/gpio_control/gpio_control.sv" \
                        "verilog/rtl/gpio_control/gpio_control.yml" \
                        "verilog/rtl/la_control/la_control_WB.v" \
                        "verilog/rtl/la_control/la_control_Wrapper.v" \
                        "verilog/rtl/la_control/la_control.sv" \
                        "verilog/rtl/la_control/la_control.yml" \
                        "verilog/rtl/wishbone_interconnect/wishbone_arbitrator.sv" \
                        "verilog/rtl/wishbone_interconnect/wishbone_decoder.sv" \
                        "verilog/rtl/wishbone_manager/wishbone_manager.sv" \
                        "verilog/rtl/wb_wrapper.vh" \
                        "verilog/rtl/wb_interconnect.sv" \
                        "verilog/rtl/user_project_wrapper.v" \
                        "verilog/rtl/defines.v" \
                        "verilog/rtl/team_projects/team_00/src/t00_decoder_for_GPIO.sv" \
                        "verilog/rtl/team_projects/team_00/src/t00_flex_counter.sv" \
                        "verilog/rtl/team_projects/team_00/includes" \
                        "verilog/rtl/team_projects/team_00/includes" \
                        "verilog/rtl/team_projects/team_00/Makefile" \
                        "verilog/rtl/team_projects/team_00/team_00_WB.v" \
                        "verilog/rtl/team_projects/team_00/team_00_Wrapper.sv" \
                        "verilog/rtl/team_projects/team_00/team_00.sv" \
                        "verilog/rtl/team_projects/team_00/team_00.yml" \
                        "verilog/dv/make/sim.makefile" \
                        "verilog/dv/team_00/module_tests/Makefile" \
                        "verilog/dv/team_00/Makefile" \
                        "verilog/dv/team_00/team_00_tb.v" \
                        "verilog/dv/team_00/team_00.c" \
                        "Makefile" \
                        "verilog/Makefile" \
                        "verilog/dv/Makefile" \
                        "template_files/config.json" \
                        "template_files/includes" \
                        "template_files/Makefile_dv" \
                        "template_files/Makefile_dv_module" \
                        "template_files/Makefile_rtl" \
                        "template_files/team_tb.v" \
                        "template_files/team_Wrapper.sv" \
                        "template_files/team.c" \
                        "template_files/team.sv" \
                        "template_files/team.yml" \
                        "openlane/user_project_wrapper/config.json" \
                        "def/user_project_wrapper.def" \
                        "gds/user_project_wrapper.gz.gds" \
                        "lef/user_project_wrapper.lef" \
                        "lib/user_project_wrapper.lib" \
                        "mag/user_project_wrapper.mag" \
                        "mag/user_project_wrapper.gz.mag" \
                        "sdc/user_project_wrapper.sdc" \
                        "spef/user_project_wrapper.spef" \
                        "spef/multicorner/user_project_wrapper.min.spef" \
                        "spef/multicorner/user_project_wrapper.max.spef" \
                        "spef/multicorner/user_project_wrapper.nom.spef" \
                        "spi/user_project_wrapper.spi" \
                        "def/ffram.def" \
                        "gds/ffram.gz.gds" \
                        "lef/ffram.lef" \
                        "lib/ffram.lib" \
                        "mag/ffram.mag" \
                        "mag/ffram.gz.mag" \
                        "sdc/ffram.sdc" \
                        "spef/ffram.spef" \
                        "spef/multicorner/ffram.min.spef" \
                        "spef/multicorner/ffram.max.spef" \
                        "spef/multicorner/ffram.nom.spef" \
                        "spi/ffram.spi" \
                        )

        # Initialize a flag to detect if any disallowed files were changed
        DISALLOWED_FILE_CHANGE_FOUND=false

        echo "Checking for blocked files..."

        # Check each file and list problems
        for FILE in "${BLOCKED_FILES[@]}"; do
          if grep -qx "$FILE" changed_files.txt; then
            echo "ERROR: Commit includes changes to shared file: $FILE"
            DISALLOWED_FILE_CHANGE_FOUND=true
          fi
        done

        if [ "$DISALLOWED_FILE_CHANGE_FOUND" = true ]; then
          echo "Push includes blocked files. Failing the workflow."
          exit 1
        else
          echo "No blocked files were changed."
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r .github/scripts/requirements.txt

    - name: Confirm Python Environment
      run: python ./.github/scripts/test_environment.py

    - name: Check New Files
      run: python .github/scripts/check_new_files.py

    - name: Module Naming Check
      run: python ./.github/scripts/module_naming_test.py
